#

title: Quant Island Website
email: your-email@example.com
description:
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

plugins:
  - jekyll-feed

  #
# exclude:

#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
